### ISSUE TITLE
Use native matchers

### ISSUE THREAD

**Issue by bdrobinson** [cartant/rxjs-marbles#13]
This library is great, thanks! I've never been able to satisfactorily test observables before but this seems to work really well.

I'm using Jest, and it has some really great native matchers built-in for pretty-printing deep object comparisons. Is it possible to use these instead of the default matcher?

**Comment by cartant** [comment]
At the moment, no, it's not possible, but it's a reasonable request and should be straightforward to add. I will give it some thought.

**Comment by cartant** [comment]
I've added a `frameworkMatcher` configuration option. And in v2.3.0, the option will default to `true` for Jest. Note that for this to happen, `rxjs-marbles` will need to be imported like this:

```ts
import { marbles } from 'rxjs-marbles/jest';
```

**Comment by bdrobinson** [comment]
Ah that's **perfect**, thanks very much for that! Sorry for the slow reply, I was away over Christmas.

**Comment by cartant** [comment]
No worries.

**Comment by Maximaximum** [comment]
@cartant unfortunately, the documentation for `frameworkMatcher` is totally missing. How is it supposed to be used? E.g., I need to be able to use `expect(storage.setItem).toHaveBeenCalledTimes(1)` (I'm using jasmine). How do I do that?

Thanks
