### ISSUE TITLE
Object property order and deep equals: expected behavior?

### ISSUE THREAD

**Issue by morphatic** [cartant/rxjs-marbles#28]
Fantastic library. Thank you!!!!

I have a question about object comparison. I'm using [`@ngrx/effects`](https://github.com/ngrx/platform/blob/master/docs/effects/README.md) in an Angular project. I'm using Jest as my testing framework. I have a class called `UserEffects` that listens for login attempts and deals with the side effects:

```typescript
@Injectable()
export class UserEffects {
  // Listen for and handle login events
  @Effect() login$: Observable<Action> = this.action$.pipe(
    ofType('[User] Start Login'),
    mergeMap(() => this.auth.login().pipe(
      map((res: AuthResult) => ({ type: '[User] Successful Login', payload: res })),
      catchError(() => of({ type: '[User] Failed Login' }))
    ))
  );
  constructor(private action$: Actions, private auth: AuthService) {}
}
```

I've also got a bunch of helper classes that inherit from `Action` that can be used to generate actions, e.g.

```typescript
export class LoginSuccess implements Action {
  readonly type = UserActionTypes.LoginSuccess;
  constructor(public payload: AuthResult) {}
}
```

My **DESIRED** test looks like this:

```typescript
it("should catch login attempts", marbles((m) => {
  const authRes = { accessToken: '12345', idToken: '67890', refreshToken: 'abcde' } as AuthResult;
  const loginStart = new UserActions.LoginStart();
  const loginSuccess = new UserActions.LoginSuccess(authRes); // <-- THIS DOES NOT WORK
  action$        = m.cold("a---", { a: loginStart } );
  const response = m.cold("--r-", { r: authRes } );
  const expected = m.cold("--b-", { b: loginSuccess } );
  auth.login = jest.fn(() => response);

  m.expect(fx.login$).toBeObservable(expected);
}));
```

However, when I run this test, I get output that looks like this:

```
    Expected
    	{"frame":20,"notification":{"kind":"N","value":{"type":"[User] Successful Login","payload":{"accessToken":"12345","idToken":"67890","refreshToken":"abcde"}},"hasValue":true}}

    to deep equal
    	{"frame":20,"notification":{"kind":"N","value":{"payload":{"accessToken":"12345","idToken":"67890","refreshToken":"abcde"},"type":"[User] Successful Login"},"hasValue":true}}
```

If you look at these closely, you can see that the **ONLY** difference between the actual and expected values is the order of the properties. If I re-write my test like this...

```typescript
it("should catch login attempts", marbles((m) => {
  const authRes = { accessToken: '12345', idToken: '67890', refreshToken: 'abcde' } as AuthResult;
  const loginStart = new UserActions.LoginStart();
  const loginSuccess = { type: '[User] Successful Login', payload: authRes }; // <-- THIS WORKS!!
  action$        = m.cold("a---", { a: loginStart } );
  const response = m.cold("--r-", { r: authRes } );
  const expected = m.cold("--b-", { b: loginSuccess } );
  auth.login = jest.fn(() => response);

  m.expect(fx.login$).toBeObservable(expected);
}));
```

...my tests pass.

Is there any way to specify a different function for performing object comparison? I expect that there's some way I could use `configure()` or `marbles()` to specify this, but I couldn't quite figure it out.

**Comment by morphatic** [comment]
Here's another example.

```typescript
it("should catch failed login attempts", marbles((m) => {
  const loginStart = new UserActions.LoginStart();
  const loginFail  = new UserActions.LoginFailure();
  action$        = m.cold("a---", { a: loginStart } );
  const response = m.cold("--#-" );
  const expected = m.cold("--b-", { b: loginFail } );
  auth.login = jest.fn(() => response);

  m.expect(fx.login$).toBeObservable(expected);
}));
```

Yields:

```
 FAIL  src/app/users/effects/index.spec.ts (23.503s)
  User Effects
    ✕ should catch failed login attempts (743ms)
  ● User Effects › should catch failed login attempts
    Expected
    	{"frame":20,"notification":{"kind":"N","value":{"type":"[User] Failed Login"},"hasValue":true}}
    to deep equal
    	{"frame":20,"notification":{"kind":"N","value":{"type":"[User] Failed Login"},"hasValue":true}}
```

But this:

```typescript
it("should catch failed login attempts", marbles((m) => {
  const loginStart = new UserActions.LoginStart();
  const loginFail  = { "type":"[User] Failed Login" };
  action$        = m.cold("a---", { a: loginStart } );
  const response = m.cold("--#-" );
  const expected = m.cold("--b-", { b: loginFail } );
  auth.login = jest.fn(() => response);

  m.expect(fx.login$).toBeObservable(expected);
}));
```

Succeeds. 

In this case, there is no issue of object properties being in a different order. The expected and actual values appear to be the same in the first example, and yet the test fails. What is the difference between using a class constructor and object literal for comparisons?

**Comment by cartant** [comment]
That seems strange, I would not have thought that ordering would be an issue.

The [matcher](https://github.com/cartant/rxjs-marbles/blob/v2.3.2/source/matcher.ts) that was copied from the RxJS repo only uses stringify when it's [formatting its output](https://github.com/cartant/rxjs-marbles/blob/v2.3.2/source/matcher.ts#L64-L68). To perform the comparisonm lodash's [`isEqual`](https://github.com/cartant/rxjs-marbles/blob/v2.3.2/source/matcher.ts#L58) function is used and it should disregard property orderings.

**Comment by cartant** [comment]
If you are using Jest, you might want to try it with Jest's matchers. See this issue: https://github.com/cartant/rxjs-marbles/issues/13.

**Comment by morphatic** [comment]
Using the Jest matchers seems to have taken care of the issue. Woohoo!!
