### ISSUE TITLE
Jest output prettiness is gone

### ISSUE THREAD

**Issue by Hetty82** [cartant/rxjs-marbles#34]
Though it works fine, the Jest output compared to a test using jasmine-marbles is missing a lot of flavor (see attached images). I especially miss the coloured diff (frame). Will this be improved?

<img width="688" alt="screen shot 2018-03-29 at 13 56 31" src="https://user-images.githubusercontent.com/2639069/38087642-253bc5a4-3359-11e8-81b9-3be40dcb9014.png">
<img width="658" alt="screen shot 2018-03-29 at 13 56 40" src="https://user-images.githubusercontent.com/2639069/38087649-27f52312-3359-11e8-83a4-c78283612aab.png">

**Comment by cartant** [comment]
Have a look at #13.

**Comment by Hetty82** [comment]
Thanks! 😃

**Comment by cartant** [comment]
No worries. And improving the docs to mention it is on my TODO list.

**Comment by cartant** [comment]
Closing this as the next version - which will be published along with RxJS v6 - will include improved docs that mention test-framework-specific imports.
