### ISSUE TITLE
Docs around how many frames are required

### ISSUE THREAD

**Issue by inorganik** [cartant/rxjs-marbles#46]
Hi, I hope this issue is constructive as I don't want to clutter the issues with a help request. I am just trying to understand better why dashes added here or removed there will cause a test to fail or succeed. Take this example where I am testing an NgRx effect. This is the effect:
```ts
  @Effect()
  insert: Observable<Action> = this.actions$
    .ofType<InsertEntity>(EntityActionTypes.InsertEntity)
    .pipe(
      exhaustMap((action) =>
        this.service.create(action.payload.entity).pipe(
          map((entity: Entity) => new InsertEntitySuccess({ result: entity })),
          catchError(({ message }) =>
            of(new InsertEntityFail({ error: message }))
          )
        )
      )
    );
```
This test will pass ✅:
```ts
  it('should return InsertSuccess action with entity on success', () => {
        const entity = generateEntity();
        const insertAction = new InsertEntity({ entity: entity });
        const successAction = new InsertEntitySuccess({ result: entity });

        actions = hot('i-', { i: insertAction });
        service.create.and.returnValue(cold('-e|', { e: entity }));
        const expected = cold('-s', { s: successAction });

        expect(effects.insert).toBeObservable(expected);
      });
```
I can add another dash to `actions` and it will still pass ✅
```ts
actions = hot('i--', { i: insertAction }); 
```
However if I add a dash in front, it fails ❌Error: `Expected $[0].frame = 10 to equal 20.` (??)
```ts
actions = hot('-i--', { i: insertAction }); 
```
Unless I _add_ an additional dash to the expected, now it passes ✅
```ts
actions = hot('-i--', { i: insertAction }); 
service.create.and.returnValue(cold('-e|', { e: entity }));
const expected = cold('--s', { s: successAction });
```
Therefore it's a process of trial-and-error, removing and adding dashes, and I have no real understanding why `x` number of dashes are required, or where. 

In addition, I can change hot to cold and it still passes in most cases, I understand what hot and cold observables are, but I don't understand when I need to use hot and cold marbles in tests. 

Any kind of info you can provide to make this less of a trial-and-error process is much appreciated :)

**Comment by cartant** [comment]
For more information on marble testing, you should refer to the [documentation](https://github.com/ReactiveX/rxjs/blob/master/doc/marble-testing.md) in the RxJS repo.

The `rxjs-marbles` package is (now) basically just a thin wrapper around `TestScheduler.run`, so all of the documentation is applicable to this marble testing done with this package.

I'd recommend writing marble tests so that the marble diagrams are aligned, like this:

```ts
it('should return InsertSuccess action with entity on success', () => {
  const entity = generateEntity();
  const insertAction = new InsertEntity({ entity: entity });
  const successAction = new InsertEntitySuccess({ result: entity });

  actions = hot(         'i-',  { i: insertAction });
  const result = cold(   '-e|', { e: entity }));
  const expected = cold( '-s',  { s: successAction });

  service.create.and.returnValue(result);
  expect(effects.insert).toBeObservable(expected);
});
```

Note that the `result` observable is going to be emitted with `i` is emitted, so like it up with that.

Using `cold` to declare the `expected` observable is just for convinience - so that all of the diagrams and their associated values are in one place. You could also do it like this:

```ts
it('should return InsertSuccess action with entity on success', () => {
  const entity = generateEntity();
  const insertAction = new InsertEntity({ entity: entity });
  const successAction = new InsertEntitySuccess({ result: entity });

  actions = hot(         'i-',  { i: insertAction });
  const result = cold(   '-e|', { e: entity }));
  const expected =       '-s';

  service.create.and.returnValue(result);
  expect(effects.insert).toBeObservable(expected, { s: successAction });
});
```

Adding a dash to the end doesn't make any difference to your test, as there is nothing emitted after the added dash and you are not testing to see whether completion or unsubscription happens at a certain point in time, so this is fine:

```ts
it('should return InsertSuccess action with entity on success', () => {
  const entity = generateEntity();
  const insertAction = new InsertEntity({ entity: entity });
  const successAction = new InsertEntitySuccess({ result: entity });

  actions = hot(         'i--', { i: insertAction });
  const result = cold(   '-e|', { e: entity }));
  const expected = cold( '-s',  { s: successAction });

  service.create.and.returnValue(result);
  expect(effects.insert).toBeObservable(expected);
});
```

If you add a dash in front of `i` and realign the `result` observable - as it will be returned when `i` is emitted - you'll see the problem:

```ts
it('should return InsertSuccess action with entity on success', () => {
  const entity = generateEntity();
  const insertAction = new InsertEntity({ entity: entity });
  const successAction = new InsertEntitySuccess({ result: entity });

  actions = hot(         '-i--', { i: insertAction });
  const result = cold(    '-e|', { e: entity }));
  const expected = cold( '-s',   { s: successAction });

  service.create.and.returnValue(result);
  expect(effects.insert).toBeObservable(expected);
});
```

`s` isn't going to be emitted when it's expected to be. A dash needs to be added to align it with the `e` emission:

```ts
it('should return InsertSuccess action with entity on success', () => {
  const entity = generateEntity();
  const insertAction = new InsertEntity({ entity: entity });
  const successAction = new InsertEntitySuccess({ result: entity });

  actions = hot(         '-i--', { i: insertAction });
  const result = cold(    '-e|', { e: entity }));
  const expected = cold( '--s',  { s: successAction });

  service.create.and.returnValue(result);
  expect(effects.insert).toBeObservable(expected);
});
```

Hopefully, that makes sense.

**Comment by dcanning** [comment]
new location for rxjs marble testing documentation:
https://github.com/ReactiveX/rxjs/blob/master/docs_app/content/guide/testing/marble-testing.md
