### ISSUE TITLE
Visual marble failure

### ISSUE THREAD

**Issue by jscti** [cartant/rxjs-marbles#59]
Hi there,

Is there a visual failure report with a marble view possible with this lib ? Like for example :
```
Error :
Source: "---a--b--c"
Expected: "a--b--c"
```

Instead of the array diff view :

```
Error :
Expected 
        {"frame":6,"notification":{"kind":"N","value":1,"hasValue":true}}
        {"frame":12,"notification":{"kind":"N","value":1,"hasValue":true}}
        {"frame":18,"notification":{"kind":"N","value":1,"hasValue":true}}
        {"frame":24,"notification":{"kind":"N","value":1,"hasValue":true}}
        {"frame":30,"notification":{"kind":"N","value":1,"hasValue":true}}
        {"frame":36,"notification":{"kind":"N","value":1,"hasValue":true}}
        {"frame":36,"notification":{"kind":"C","hasValue":false}}
      
      to deep equal 
        {"frame":6,"notification":{"kind":"N","value":1,"hasValue":true}}
        {"frame":6,"notification":{"kind":"C","hasValue":false}}
      : Expected false to be truthy.
```

Thanks

**Comment by cartant** [comment]
No. There isn't. This library just wraps the `TestScheduler` it doesn't re-render the actual output as a marble diagram.

There are a number of reasons why that would be tricky:

* Marble diagrams can now include explicit, numeric times.
* For non-character values, a map would have to be provided.

**Comment by kosich** [comment]
Maybe we could create a standalone API to compare particularly string representations for simple cases.
It would also throw for explicit timing & non-char values.
E.g.:

```js
m.diagrams.equal(m.hot('-1-|'), '-2-|')
```

```
Error:
Expected -2-|
Received -1-|
```

Is it even possible? What do you think?

_P.S: I didn't dig the source code so I might be missing something obvious here_
_P.P.S: thx for the library!_

**Comment by cartant** [comment]
Closing this because any such feature would need to be implemented in the `TestScheduler` - around which this package is little more than a thin wrapper.
