### ISSUE TITLE
The timing is not correct when using parentheses

### ISSUE THREAD

**Issue by sengmann** [cartant/rxjs-marbles#66]
I have the following minimal example that I think should work:

```typescript
it("should succeed", marbles((m) => {
        const a$ = m.cold("-a|");
        const b$ = m.cold("-1|");

        const o$ = m.cold("-(a1)|");

        const result = merge(a$, b$);
        m.expect(result).toBeObservable(o$);
    }));
```

The result ends as expected in frame 2, but o$ ends only in frame 5.

Are synchronous notifications possible?

**Comment by cartant** [comment]
Not a bug. Read about 'sync groupings' in the RxJS marble testing docs: https://github.com/ReactiveX/rxjs/blob/master/docs_app/content/guide/testing/marble-testing.md#marble-syntax

> While it can be counter-intuitive at first, after all the values have synchronously emitted time will progress a number of frames equal to the number of ASCII characters in the group, including the parentheses.

**Comment by sengmann** [comment]
Many thanks for the quick answer. I was not aware of the reason why the frames keep running. Of both solutions the first one looks a little more intuitive. But the lead is minimal.
