### ISSUE TITLE
Prefer strict equality comparison over the regular one

### ISSUE THREAD

**Issue by karol-majewski** [cartant/rxjs-marbles#67]
Hello and thank you for your wonderful tool.

**The problem**

The Observable I'm testing returns an object. That object is not allowed to have values explicitly set to `undefined` — in case the value does not exist, I want to skip the field instead.

My Marble tests reflect that. I expect only one property.

```ts
const expected$ = m.cold(expectedM, {
  a: {
    name: 'Bob',
  },
});

m.expect(actual$).toBeObservable(expected$);
```

However, the output emitted by `actual$` looks like that:

```ts
  a: {
    name: 'Bob',
    age: undefined,
  },
```

This change was not detected by Jest, but it did break my code.

**The solution**

When performing deep equality comparison. prefer `toStrictEqual` over `toEqual`.

If we replace `toEqual` with `toStrictEqual`, my excess properties are detected, which makes the tests fail as expected. This change would need to be made here:

https://github.com/cartant/rxjs-marbles/blob/75b646c92765e24f42119ba1e2855946ff391811/source/jest/index.ts#L43

If you agree with that change, I can open a PR and get it done — just say the word.

**Comment by cartant** [comment]
Sounds good to me. Thanks.
