### ISSUE TITLE
How to do custom checks after an observable finished?

### ISSUE THREAD

**Issue by Maximaximum** [cartant/rxjs-marbles#69]
I'm using Jasmine and I need to do some additional checks after the observable checks. Ie,
```typescript
m.expect(effects.openSequence).toBeObservable(m.cold('(1234)', expectedActions));
expect(activityService.trackFinalization).toHaveBeenCalled();
```

How do I do that?

**Comment by cartant** [comment]
Make an `m.flush();` call before your additional checks. There is an implicit `flush` when the test callback returns. You can perform an explicit flush and then do whatever. E.g. https://github.com/cartant/rxjs-etc/blob/048e11eff7ab53a526834fbd4cc926528dcf974e/source/operators/tapSubscribe-spec.ts#L13-L25

**Comment by Maximaximum** [comment]
Thanks a lot! It works.

Maybe it would make sense to add information to documentation so that other users can easily find this info? Otherwise, this issue can be closed I think.

**Comment by cartant** [comment]
These days, the package this just a thin wrapper around `TestScheduler#run` and that's mentioned in the README. The `flush` behaviour is described in the [official docs](https://github.com/ReactiveX/rxjs/blob/master/docs_app/content/guide/testing/marble-testing.md#api). If there isn't already a link to said docs in the README, I'll add one.

**Comment by cartant** [comment]
Added some links to the official docs and fixed several existing links that were broken. Thanks.
