### ISSUE TITLE
Configuration assertDeepEqual cannot be overwritten.

### ISSUE THREAD

**Issue by iamchangming** [cartant/rxjs-marbles#70]
const { marbles } = configure({ assertDeepEqual: (a, e) => expect(a).toEqual(e) });

With the configure above, test still fails at
expect(received).toStrictEqual(expected) // deep equality

This is due to the following, see the comment:
https://github.com/cartant/rxjs-marbles/commit/c12ce8294d82564a44d08e8f9c1a09e97bce9860#diff-1952774788677e126ff25b73d61b4602

**Comment by cartant** [comment]
Yeah, you are right. And that change - to using strict - should have been a major version bump, too.

**Comment by cartant** [comment]
5.0.6 has been published. It reverts the default of `toStrictEqual` for Jest and allows for default and framework-specific configurations to be overridden by callers. I will be publishing version 6 that includes the defaulting to `toStrictEqual` for Jest, as I think that ought to be the preferred default.
