### ISSUE TITLE
Use marbles and fakeSchedulers together

### ISSUE THREAD

**Issue by tomdaniel0x01** [cartant/rxjs-marbles#73]
I'd love to use marbles and fakeSchedulers together.

Why can't testSchedulers just be a configuration option for marbles? I have the expectation that if observable virtual time is being faked that JavaScript timers should also be faked simultaneously.

There must be a lot of code in the wild with both JavaScript based timers and observable based timers that needs to be tested.

Related: https://github.com/cartant/rxjs-marbles/issues/62

**Comment by cartant** [comment]
The reason why this isn't possible is explained in this comment https://github.com/cartant/rxjs-marbles/issues/62#issuecomment-512042175 - in the issue you referenced - and in the article linked therein.

These days, `rxjs-marbles` is just a thin wrapper around `TestScheduler#run` and it's the `TestScheduler` that implements marble tests. That is not going to change.

**Comment by cartant** [comment]
Thinking about this more, it might be possible to align virtual and fake time, but it would depend upon changes being made to the `TestScheduler`. There has been some discussion about allowing for time providers to be patchable and configurable - i.e. instead of the scheduling implementations calling `Date.now()` or `performance.now()` directly (by default), they'd call an intermediate, patchable/configurable API. It's conceivable that this API could allow for the configuration of 'setter' that the `TestScheduler` could call when it advances its virtual time. If that were to happen, `rxjs-marbles` could use it to synchronize virtual and fake time. There are higher priorities though, ATM, so even if this were to happen, it wouldn't be anytime soon.

**Comment by tomdaniel0x01** [comment]
Thanks for the reply and consideration! `fakeSchedulers` has been a godsend even though I can't do marble testing.

> Thinking about this more, it might be possible to align virtual and fake time, but it would depend upon changes being made to the `TestScheduler`. There has been some discussion about allowing for time providers to be patchable and configurable - i.e. instead of the scheduling implementations calling `Date.now()` or `performance.now()` directly (by default), they'd call an intermediate, patchable/configurable API. It's conceivable that this API could allow for the configuration of 'setter' that the `TestScheduler` could call when it advances its virtual time. If that were to happen, `rxjs-marbles` could use it to synchronize virtual and fake time. There are higher priorities though, ATM, so even if this were to happen, it wouldn't be anytime soon.

... and from https://medium.com/angular-in-depth/rxjs-testing-with-fake-time-94114271eed2
> Unfortunately, that’s not always easy to do. And using the VirtualTimeScheduler won’t help if the code under test also includes time-related, non-RxJS code, as the virtual and fake time concepts differ significantly.
>
>To solve this problem, I’ve added a fakeSchedulers function to rxjs-marbles, so that tests can use fake time for situations in which a marble test would be too complicated to write.

I thought fake time and virtual time were already being aligned through `fakeSchedulers` as mentioned in the quote above in your article. This lead me to believe that the same thing was possible through `marbles`. I haven't dug into the source of this library so I may be speaking with too much ignorance, but you say that `marbles` is just a wrapper for the RxJS implementation. So does this mean that there's no way to "interfere" with what RxJS is doing within a blackbox without that RxJS API change?

It seems that you could sync fake time and virtual time using the [time progression syntax](https://rxjs-dev.firebaseapp.com/guide/testing/marble-testing#time-progression-syntax) (or default frame time) by parsing the marble diagram input and advancing fake time in parallel the same way you do through `fakeSchedulers`.

**Comment by cartant** [comment]
> I haven't dug into the source of this library so I may be speaking with too much ignorance, but you say that marbles is just a wrapper for the RxJS implementation.

Once upon a time, marble testing was something that was more or less internal to RxJS. `rxjs-marbles` wrapped the weirdness into a friendlier API that was test framework agnostic - unlike, say, `jasmine-marbles`. Sometime after that, `TestSchduler#run` was added to RxJS and `rxjs-marbles` was re-implemented to use `TestSchduler#run` - becoming little more that a thin wrapper around it.

> It seems that you could sync fake time and virtual time...

Yeah, the sync would need to happen in the `TestScheduler`.

**Comment by cartant** [comment]
@tomdaniel0x01Do you have an example of a test - that use marbles and fake time - that you would be wanting to write?

**Comment by cartant** [comment]
Closing this. Implementing it would be possible - without upstream changes - but I don't see that this would be an especially compelling feature.

**Comment by tomdaniel0x01** [comment]
I'm writing a production app with RxJS and there are many parts of code that use both Observables and JavaScript timers that need to be tested. It's very unfortunate that I can't test the code using marble testing.

@cartant I really wish I had the time to help out more! In a few months from now I might be able to refactor some of my tests into something you are looking for that would help push this feature forward.

For now I'll just have to use the convoluted method of turning observables into promised and tracking the execution order through an array.
