### ISSUE TITLE
Problems testing observables that emit arrays or objects with other observables.

### ISSUE THREAD

**Issue by fcostarodrigo** [cartant/rxjs-marbles#76]
It looks like when the observable emits another observable the tests work fine, but when instead we emit an object or an array containing the same observables the tests fail.

https://replit.com/@fcostarodrigo/MarblesHighOrderObservables#test.js

**Comment by cartant** [comment]
These days, this package is a thin wrapper around the RxJS `TestScheduler`'s run mode. So if the `TestScheduler` doesn't support an expectation, this package doesn't either.

**Comment by fcostarodrigo** [comment]
Thanks for the fast response. I will investigate the issue later using TestScheduler.

**Comment by fcostarodrigo** [comment]
That happens with test scheduler as well. Same issue.

https://github.com/ReactiveX/rxjs/issues/6243
